### ISSUE TITLE
Missing PTC Basemaps

### ISSUE THREAD

**Issue by impittman** [impittman/PTC-Inspection-Field-Tool#1]
According to the requirements "The system will be configured to include the base map options provided within the PTC ArcGIS Online environment." After reviewing the PTC ArcGIS Online base maps, the following are missing: 
Imagery Hybrid
Navigation
Streets (Night)

**Comment by dobrochtaKCI** [comment]
During development and testing the applications are being hosted on KCI's AGO and shared with the PTC. We will not have access to these basemaps until the application is hosted on the PTC AGO account

**Comment by dobrochtaKCI** [comment]
I was able to get access to these basemaps, and have included them in the new collector map.
