### ISSUE TITLE
Adding additional Maintenance Action Item Records

### ISSUE THREAD

**Issue by impittman** [impittman/PTC-Inspection-Field-Tool#10]
It is a bit unclear how to add more Maintenance Action Items to the Component. From several testing attempts, it became clear it is by using the plus sign under Maintenance Photos. More clarity is needed here for the end-user, either by adding text/rearranging the location of the "+" sign etc.

![photo or maintenance](https://user-images.githubusercontent.com/16418393/41208925-3b44e5cc-6d17-11e8-8dd2-d12b19102a97.png)

**Comment by leeensminger** [comment]
@impittman My thought is that this will be communicated via training and documentation (we have a whole other task for documentation).  In discussing the workflow with stakeholders, after understanding the process, they seemed to understand how this works - as you did.  Does it seem reasonable that this workflow works, if it is preceded by documentation and training?

**Comment by impittman** [comment]
@leeensminger I think if it is heavily documented, i.e. case example, photos, workflow, then it will work. Its placement is what predominately makes it unclear on the true functionality.

**Comment by dobrochtaKCI** [comment]
The only way I can update the visual for this would be to reorder the questions. I can move the photo question above the comment question if we think it would help visually?

**Comment by impittman** [comment]
Honestly, I think it may take away some of the confusion as to if a user is adding a photo vs a maintenance record by hitting the "+"  if it is moved around a bit.

**Comment by dobrochtaKCI** [comment]
Currently, we do not see the need to rearrange the question ordering until further communication with PTC
