### ISSUE TITLE
Photos are not named correctly

### ISSUE THREAD

**Issue by impittman** [impittman/PTC-Inspection-Field-Tool#12]
Requirements state "The system will be configured to rename each maintenance photo as [component]_MAINT_PHOTO-[date]-[six-digit system number]." 

Photos names need to be updated. Currently, the Photos save as the following:
![bad photo name](https://user-images.githubusercontent.com/16418393/41209107-c791da5c-6d18-11e8-80ee-085f0aa98200.png)

**Comment by dobrochtaKCI** [comment]
@leeensminger I know you originally saw the photo names using a different format. 

![d847213](https://user-images.githubusercontent.com/37631196/41290864-17a9479c-6e1c-11e8-9ef7-57f7f363a3ae.PNG)

Now it appears Survey 123 is appending a globalID to the photo field name. I have no control over how Survey123 is generating photo names other than the field name I provide. I will continue to monitor/ search for some logic to the change in format.

**Comment by leeensminger** [comment]
As of this comment this appears to be working as designed.
