### ISSUE TITLE
Condition Ratings Scale is not the same for each component

### ISSUE THREAD

**Issue by impittman** [impittman/PTC-Inspection-Field-Tool#13]
In Survey123, the Condition Rating Scale is different for various components. Sometimes, only one or two letters exist on the rating scale, other times it shows A,B,C,D,F. Is there logic to only show one letter vs all? If not, should this be corrected?

All Letters:
![all ratings](https://user-images.githubusercontent.com/16418393/41209223-99916bf8-6d19-11e8-9ac9-0bf9e2b28937.png)

Only 1 Letter for Rating:
![rating not a b c](https://user-images.githubusercontent.com/16418393/41209204-7940bcaa-6d19-11e8-9ad3-82d4b5c50ff1.png)

**Comment by leeensminger** [comment]
@impittman Yes, there is logic here.  It is based on the Maintenance Type selected.  So the condition ratings are a sliding scale based on the Maint Type... Routine Maintenance translates to an A or B, Redesign translates to an F, and those in between are appropriately filtered.

**Comment by impittman** [comment]
@leeensminger if I need to confirm these are assigned correctly, let me know. if not I will close

**Comment by leeensminger** [comment]
@impittman They're good, no need to verify these, thanks
