### ISSUE TITLE
Condition Rating Scales are not present in Emergency Spillways

### ISSUE THREAD

**Issue by impittman** [impittman/PTC-Inspection-Field-Tool#14]
Not all components of the Emergency Spillway form have rating scales present. It is a overlapping straight-line at the Rating Scale area (see below).

No Scale Present:
![condition rating missing spillway crest](https://user-images.githubusercontent.com/16418393/41209293-205ef9b6-6d1a-11e8-8d98-54f5a4857a33.png)

**Comment by leeensminger** [comment]
@impittman Was this found to be working?  I'm seeing this issue in Spillway Crest

**Comment by impittman** [comment]
@leeensminger it is working, I believe it was due to not marking a maintenance type after further testing, so I closed it

**Comment by leeensminger** [comment]
@dobrochtaKCI This is not working for spillway crests

**Comment by dobrochtaKCI** [comment]
I have updated this in the new version of the tool, but it is not fully published and shared.

**Comment by dobrochtaKCI** [comment]
Spillway crest is no longer an inspection component.
