### ISSUE TITLE
Change Colors on Condition Rating Scale

### ISSUE THREAD

**Issue by impittman** [impittman/PTC-Inspection-Field-Tool#15]
If this has not been set in stone by PTC, consider updating the color scheme on the Conditions Rating form. The letter "B" does not stand out well.

![all ratings](https://user-images.githubusercontent.com/16418393/41209322-55ce7b08-6d1a-11e8-8f64-2e6f28ebcc70.png)

**Comment by dobrochtaKCI** [comment]
I have made the Green used for the letter "B" darker. The survey is not fully published and shared until all updates are made.

**Comment by dobrochtaKCI** [comment]
New survey with updated color has been published and shared
