### ISSUE TITLE
Somtimes prompted to sign in to submit inspection

### ISSUE THREAD

**Issue by impittman** [impittman/PTC-Inspection-Field-Tool#16]
I am sometimes prompted to sign-in when I submit inspections: Is this normal?
![inspection signin](https://user-images.githubusercontent.com/16418393/41209809-602c2bb0-6d1d-11e8-84e3-642871398f7d.png)

**Comment by dobrochtaKCI** [comment]
Yes you need to be signed into AGO to submit a survey. It should prompt you to sign in if you were not signed in prior to sending. If you were signed in prior to sending it shouldn't need to ask you to sign in again.

**Comment by impittman** [comment]
This definitely happened while fully signed in to Survey123 on more than one occasion. If it is just a simple nuisance and not an error, I suppose we can ignore. 

@leeensminger Perhaps this should be addressed in the user guide so users are not confused on why they are asked to re-sign in (or initially sign in if the case) to submit the inspection.

**Comment by leeensminger** [comment]
@impittman Noted for the documentation.  I haven't seen this, and is more of a function of the software itself, so let's continue to monitor this, close the issue, and document any necessities in the documentation.
