### ISSUE TITLE
Maintenance Photo Required if maintenance action is selected

### ISSUE THREAD

**Issue by dobrochtaKCI** [impittman/PTC-Inspection-Field-Tool#17]
Confirm a maintenance photo is required if a maintenance action is selected

**Comment by dobrochtaKCI** [comment]
This can be done but at the cost of being able to associate photos to no maintenance components. This is on hold until further discussion with the client.

**Comment by dobrochtaKCI** [comment]
Maintenance photos are disabled if no maintenance action is selected. See #38

**Comment by leeensminger** [comment]
Looks good
