### ISSUE TITLE
Basemap Default Imagery needs to be updated

### ISSUE THREAD

**Issue by impittman** [impittman/PTC-Inspection-Field-Tool#2]
According to the requirements, "The system will be configured to display the "Imagery with Labels" base map by default."
Currently, the default I see is just "Imagery" in Collector.

**Comment by dobrochtaKCI** [comment]
I updated to use imagery with labels. The requirements guide will need to be updated to imagery without labels if the tool will be used in a disconnected environment. Imagery with labels is supported for disconnected use.

**Comment by leeensminger** [comment]
Appears resolved
