### ISSUE TITLE
Swale without Forebay - update Ratings header

### ISSUE THREAD

**Issue by leeensminger** [impittman/PTC-Inspection-Field-Tool#20]
See image - in the Swale without Forebay component, the Ratings header should be updated to read "Swale without Forebay Ratings".  Please ensure capitalization is consistent with other components.

![image](https://user-images.githubusercontent.com/4103847/41763470-5c076452-75cc-11e8-9909-2c68ab354d49.png)

**Comment by dobrochtaKCI** [comment]
Updated Text

**Comment by leeensminger** [comment]
tested ok
