### ISSUE TITLE
Swale without Forebay - formatting

### ISSUE THREAD

**Issue by leeensminger** [impittman/PTC-Inspection-Field-Tool#27]
"Without" should be "without" to be consistent:
![image](https://user-images.githubusercontent.com/4103847/41764086-1046fbc0-75ce-11e8-974f-d68e5d0dddd0.png)

**Comment by leeensminger** [comment]
Same in Ratings:
![image](https://user-images.githubusercontent.com/4103847/41764150-3eecc946-75ce-11e8-9c3a-dc88f3d6b2c9.png)

**Comment by leeensminger** [comment]
Same in Ratings:
![image](https://user-images.githubusercontent.com/4103847/41764150-3eecc946-75ce-11e8-9c3a-dc88f3d6b2c9.png)

**Comment by leeensminger** [comment]
Same in Ratings:

**Comment by leeensminger** [comment]
Same in additional photos:
![image](https://user-images.githubusercontent.com/4103847/41764299-ad9c253a-75ce-11e8-9fcf-9a0125d8b1df.png)

**Comment by dobrochtaKCI** [comment]
Updated spelling consistency and capitalization of word "without"

**Comment by leeensminger** [comment]
tested ok
