### ISSUE TITLE
Fencing page

### ISSUE THREAD

**Issue by leeensminger** [impittman/PTC-Inspection-Field-Tool#29]
Change page name to "Fencing"
Rename all instances of "Gates" to "Gates/Lock"

![image](https://user-images.githubusercontent.com/4103847/41764693-e972b06e-75cf-11e8-8a55-6a7801d3e15d.png)

**Comment by dobrochtaKCI** [comment]
Update Page name and all sub-section names

**Comment by leeensminger** [comment]
tested ok
