### ISSUE TITLE
Cannot Update SCM Centroid Geometry

### ISSUE THREAD

**Issue by impittman** [impittman/PTC-Inspection-Field-Tool#3]
According to the requirements, "The system will allow the user to update geometry for an existing SCM Centroid."

I am unable to move the centroid by clicking and dragging. I also tried to update the lat/long to make it move, this did not work either.

**Comment by dobrochtaKCI** [comment]
I tested this today and I am able to move the SCM Centroid. In order to move the Centroid the user must first select the point to be moved, and begin the editing session. The user should tap the map once to move the point to the selected location. Dragging will not move the point.

**Comment by impittman** [comment]
@leeensminger  this should be highlighted in the user guide. it is not as user intuitive and describing it in the guide will help.

the methods outlined worked after a couple attempt on a mobile device.
