### ISSUE TITLE
Signage page

### ISSUE THREAD

**Issue by leeensminger** [impittman/PTC-Inspection-Field-Tool#30]
Update the "Inspect the Emergency Spillway" text to reflect 'signage'.

![image](https://user-images.githubusercontent.com/4103847/41764743-0eb5b04c-75d0-11e8-96fe-0934dbf67f63.png)

**Comment by dobrochtaKCI** [comment]
Updated the text for the group values

**Comment by leeensminger** [comment]
tested ok
