### ISSUE TITLE
First page

### ISSUE THREAD

**Issue by leeensminger** [impittman/PTC-Inspection-Field-Tool#31]
Change "SCM has Linear" ==> "SCM Has Liner?"
Convert the following fields and data elements to read-only (like the SCM Name is):

- System Location
- Access Type
- SCM Has Liner
- Permitted Dam Category
- Latitude
- Longitude

![image](https://user-images.githubusercontent.com/4103847/41765190-5a966262-75d1-11e8-940f-961a35144db3.png)

**Comment by dobrochtaKCI** [comment]
Changed the display of the fields. 

Fields must be written as text with no domains to display like SCM ID and SCM Name

**Comment by leeensminger** [comment]
tested ok
