### ISSUE TITLE
First page - SCM ID

### ISSUE THREAD

**Issue by leeensminger** [impittman/PTC-Inspection-Field-Tool#32]
I understand the point of displaying the SCM ID (to verify the relationship is in tact).  Is it possible to use SCM Name for this purpose?  If we move SCM Name up to the top, include the same text like you currently have in red... and if the SCM Name is blank, then the data didn't get pulled from Collector, which means the survey didn't launch right.  Do you agree?  If so, let's drop the SCM ID, and move SCM Name to that location.

![image](https://user-images.githubusercontent.com/4103847/41765035-e31e4524-75d0-11e8-90bf-0ada9255bc33.png)

**Comment by leeensminger** [comment]
Also SCM Name probably doesn't need the red asterisk since it's a read-only label

**Comment by dobrochtaKCI** [comment]
Yes, this is feasible, and will continue to be as long as every SCM is given a name properly when added to the system. I have hid the SCM ID and move the SCM Name field to the top of the page.

**Comment by leeensminger** [comment]
Yes, SCM Name is expected to be populated for every SCM.  Tested OK.
