### ISSUE TITLE
Collector - Lat/Long cannot be edited

### ISSUE THREAD

**Issue by leeensminger** [impittman/PTC-Inspection-Field-Tool#33]
I changed my mind about these fields.  I can see the value for stakeholders to have this data to support annual reporting, etc., so let's keep them on the polygon as well as the centroid.  I see these fields in Collector on the first page, but when I try to edit, I do not see them anymore.  Please ensure users can edit these fields in Collector as well.

Also ensure that once populated, these values are pulled correctly into Survey.

![image](https://user-images.githubusercontent.com/4103847/41765577-76f5a99e-75d2-11e8-9010-4a9481ba217d.png)

**Comment by dobrochtaKCI** [comment]
I calculated the LAT LONG fields for all of the SCM polygons. Do we really want these fields to be editable in the field? they will be able to update this information without actually changing the location of the polygon. It can also create discrepancies between the polygon and the SCM Centroid.

**Comment by leeensminger** [comment]
@dobrochtaKCI Good call, I agree with your assessment, non-editable is best.  It will be strictly calc'd on the back end via ArcGIS and/or Python through manual processes, or automated through our data management scripts maybe

**Comment by leeensminger** [comment]
tested ok
