### ISSUE TITLE
First page - Access Type

### ISSUE THREAD

**Issue by leeensminger** [impittman/PTC-Inspection-Field-Tool#35]
Why is the Access Type value in light gray strikethrough text?  This seems to be for multiple SCMs/Inspections.

![image](https://user-images.githubusercontent.com/4103847/41766207-5ba3efc8-75d4-11e8-8a9a-a179a7e22427.png)

**Comment by dobrochtaKCI** [comment]
This was a domain issue. Collector pushes the description, but the description is not a valid domain value in survey 123.  This is a read only field so I removed the domain value so the description is a valid response.
