### ISSUE TITLE
Secondary Outfall - page is blank when Inventory value = not present

### ISSUE THREAD

**Issue by leeensminger** [impittman/PTC-Inspection-Field-Tool#36]
When Secondary Outfall = No in collector, the survey form is blank.  Please include the same "nothing to inspect" text from other pages.

![image](https://user-images.githubusercontent.com/4103847/41766410-ee8d21ba-75d4-11e8-80b8-5bba78998691.png)

**Comment by dobrochtaKCI** [comment]
Note field was within the non displayed group. I moved the note outside of the group and the correct text displays.

**Comment by leeensminger** [comment]
tested ok
