### ISSUE TITLE
Summary Scores - score is not calculating correctly

### ISSUE THREAD

**Issue by leeensminger** [impittman/PTC-Inspection-Field-Tool#37]
I performed an inspection where three inventory parameters are present.  I rated two as "No Maintenance", and one as "Corrective Maintenance".  The final score should have been "Fair", but came through as "Good".

Summary scores that result in "Good" or "Poor" seem to be OK, but those that should be "Fair" are not currently working.

**Comment by dobrochtaKCI** [comment]
Changed {Score_Value} > 1 to {Score_Value} >=1 to capture a score of 1 = "Fair"

**Comment by leeensminger** [comment]
tests ok
