### ISSUE TITLE
All components - Maintenance Required / Maintenance Type

### ISSUE THREAD

**Issue by leeensminger** [impittman/PTC-Inspection-Field-Tool#38]
Maintenance Required field appears to be required at all times.  This is OK except when Maintenance Type = No Maintenance.  

As I see it, we have two options:
1. Make Maintenance Required not a required field, at all times
2. Ensure that when we populate Maintenance Required domain lists, we include a value at the top of the list for "No Maintenance".
3. Is there a way in Survey to enforce this field only when Maintenance Type <> No Maintenance?

My preference is # 3, but if that is not feasible, then # 2 is our better bet at this time.  This would result in no net action for you at this time.

![image](https://user-images.githubusercontent.com/4103847/41766687-a72c2f90-75d5-11e8-9e79-af06cd524b30.png)

**Comment by dobrochtaKCI** [comment]
I removed the maintenance required field when no maintenance is required. It is displayed initially because there is no default value for maintenance type.  @leeensminger Do you think that if no maintenance is selected than all the fields should be removed including maintenance comments and photos #17, and possibly even the condition rating in the next section, since Condition "A"is the only valid answer?

**Comment by leeensminger** [comment]
@dobrochtaKCI Yes if no maintenance is required, remove maintenance comments and maintenance photos.  Probably remove the repeater too (if feasible, not sure).  Keep the component rating and the overall component photos.

**Comment by dobrochtaKCI** [comment]
Maintenance comments and photos are also removed from display if no maintenance is selected. I can not remove the repeat ability once it is in place.

**Comment by leeensminger** [comment]
@dobrochtaKCI This tests fine and works as described.  When I submit the form though, it tells me _Maintenance Required is required_.  Is it still required even though its hidden?

My steps to get here are:
- Set 3 components as present (Observatoin well, Forest, Emergency Spillway)
- Set Obs Well and Forest as No Maintenance.  The Maintenance Required field is hidden for both of these.
- Set Emergency Spillway <> No Maintenance.  The Maintenance Required form is displayed, and I select a value.
- I apply a rating for all as needed, and hit submit
- screenshot: 
![image](https://user-images.githubusercontent.com/4103847/41784179-f004caf6-760c-11e8-9f50-7719e973dbc7.png)

**Comment by leeensminger** [comment]
tests ok
