### ISSUE TITLE
How should the lat/long fields populate when adding a Structure

### ISSUE THREAD

**Issue by impittman** [impittman/PTC-Inspection-Field-Tool#4]
Currently, when I add a new Structure, the lat/long fields rename blank, even after saving. Is the user expected to enter these values? Or should they be auto-popualted? 

After hitting submit, these fields are still blank:
![struc 2](https://user-images.githubusercontent.com/16418393/41208283-584c5426-6d11-11e8-8e3f-98dc1351d7cf.png)

Lat/Long is present at top under Structure
![struc 1](https://user-images.githubusercontent.com/16418393/41208288-6a4b1770-6d11-11e8-8b6f-4efe5d83487d.png)

**Comment by dobrochtaKCI** [comment]
There currently isn't a way to have these values auto-populated in collector without the use of an external GPS system. The user can retrieve the lat long information and manually populate these fields. The location information can be obtained for any point on the map by pressing and holding your finger on the map. A popup will display a best guess address and lat long information.
