### ISSUE TITLE
right of way layer is not active when launching web app -Req FR86.0

### ISSUE THREAD

**Issue by impittman** [impittman/PTC-Inspection-Field-Tool#49]
According to the requirement FR86.0, the Right of Way layer should be Active as default. The entire Reference Layer is defaulted to not active, thus the ROW layer is also not active upon launching. Both the utilities projects and crossings are correctly not actively showing as stated by the requirements however.

![ref layer defualt](https://user-images.githubusercontent.com/16418393/42593542-43fba1fa-853c-11e8-92f9-9f6d09337d9f.png)

**Comment by dobrochtaKCI** [comment]
Updated initial layer visibility. This is visible when page is refreshed.
