### ISSUE TITLE
Query Widget Has Errors

### ISSUE THREAD

**Issue by impittman** [impittman/PTC-Inspection-Field-Tool#50]
I attempted to Query an Inspection by SCM Name and got the following:
It states I am querying by a Name but asks for a Rating instead:

![query widget](https://user-images.githubusercontent.com/16418393/42594166-e689ee44-853d-11e8-81fa-e931e88757b6.png)

**Comment by dobrochtaKCI** [comment]
Updated filter field.  update is visible upon page refresh.

**Comment by leeensminger** [comment]
looks ok
