### ISSUE TITLE
Maintenance Repair list incorrect for Discharge Points

### ISSUE THREAD

**Issue by leeensminger** [impittman/PTC-Inspection-Field-Tool#54]
For Corrective Maintenance (Current Year), and Corrective Maintenance (Immediate):
The repair list for Current Year includes all those that is should, but it also includes several repair items from the Immediate list.  Then, the Immediate list only has two associated repair lists.  Need to move some of these repair items from one maintenance type to the other

![image](https://user-images.githubusercontent.com/4103847/43040074-b938f9ee-8d08-11e8-842a-d28deb7026ad.png)

**Comment by dobrochtaKCI** [comment]
I updated the 'cascading select'options for the discharge point maintenance lists and republished the annual inspection and field view inspection forms. You will need to delete and re-download surveys to see the changes applied.

**Comment by leeensminger** [comment]
appears resolved
