### ISSUE TITLE
Survey123 first page is confusing

### ISSUE THREAD

**Issue by impittman** [impittman/PTC-Inspection-Field-Tool#6]
The initial page to begin Survey123 is confusing. I think there needs to be some language included here to let the user know this information is not editable. Also, if a SCM does not have data associated with it, the first page in Survey123 is blank, making it appear that the user should populate the data here. These fields are locked, likely to prevent this from occurring in Survey123. However, as an end-user, the action to take in Survey123 when the page is blank is very unclear. Consider adding some text here to clarify things.

**Comment by leeensminger** [comment]
@dobrochtaKCI @impittman I suggest the inventory data be removed from this first page.  If I recall, this was a temporary setup.  At this point, I agree with Maria that it is somewhat confusing for users and is not supportive of the expected workflow.  Users should confirm this inventory data in Collector, then launch into the form.

**Comment by dobrochtaKCI** [comment]
Inventory is removed from the first page
