### ISSUE TITLE
Rain Event field is missing in Survey123

### ISSUE THREAD

**Issue by impittman** [impittman/PTC-Inspection-Field-Tool#7]
The requirements show "The system will be configured to allow the user to select a Yes/No option to indicate if a rain event occurred within the past 72 hours."

I did not see the Rain Event field within Survey123.

**Comment by dobrochtaKCI** [comment]
@leeensminger Do we want to add this back to the survey? I thought we were eliminating the weather related fields so they could be populated automatically using a weather service?

**Comment by leeensminger** [comment]
@dobrochtaKCI Agreed; the requirement will be rewritten to indicate that the system (as a whole) will capture this, but it will not be in the field tool
