### ISSUE TITLE
Editing "Present During Inspection" data is confusing

### ISSUE THREAD

**Issue by impittman** [impittman/PTC-Inspection-Field-Tool#8]
When I edit an Inspector Name in Survey123, there is no option to save my edits. Instead, I have to click Add to go to blank Inspector Name text field then click "Delete" to have my edits save and to remove the blank Inspector Record I have to add. There should be an edit option here or at minimum a save button to make this process less confusing.

Perhaps add an edit or save option here:
![no edit](https://user-images.githubusercontent.com/16418393/41208603-e28c4df0-6d14-11e8-9c6c-c3739c70c570.png)

**Comment by dobrochtaKCI** [comment]
@impittman not sure I understand the issue. What do you mean it will not save? When I enter a name here I can flip pages and when I return to the page the name entered is still present. The plus sign only needs to be selected to add another record.

**Comment by impittman** [comment]
To me, it is just hard to tell if my edits are being saved without an edit/save feature because it is free text when 1 record is present. I cannot validate my edits are saved.  Sure I can type a change, but the free text edit has no way to truly show validation that the edit saved without a save button. The only way I can ensure that my free-text edit saved is to click the plus when only one visitor is present to add a visition and then click the backwards arrow to show this edit indeed did change/save/etc. Without doing so, I have to trust my free-text edit worked since no save feature button is there as it just looks like I typed something, but does not have any way to confirm the edit worked.

**Comment by dobrochtaKCI** [comment]
Ok, I get the concern, but Survey 123 will not allow me to add button functionality such as a save or edit button into the form. This is a limitation of the product. @leeensminger  I remember they had mentioned possibly turning this into a drop down feature since they know the inspectors that ill be in the field. Do we want to go this route? My only concern is that in the future if the inspectors change this drop down list will need to be updated.

**Comment by leeensminger** [comment]
My preference is to leave as an open text field right now.  As this is a limitation of the tool, closing this issue.
