### ISSUE TITLE
Clean up message for Deleting Maintenance/Repair Actions

### ISSUE THREAD

**Issue by impittman** [impittman/PTC-Inspection-Field-Tool#9]
The current message that appears when Deleting a Maintenance/Repair Action item is confusing. It is not clear to user if they are deleting a Photo or the Maintenance/Repair Action Item due to the placement of the trashcan (see image below). It would be helpful to have more text to show what "1 of x" is being deleted.

Unclear what the Trashcan is deleting, the photo or the maintenance action item added:
![delete is](https://user-images.githubusercontent.com/16418393/41208826-62568b30-6d16-11e8-9ded-a17214f77796.png)

Clear up this message:
![delete what](https://user-images.githubusercontent.com/16418393/41208782-2d72c636-6d16-11e8-9224-2c3dc414a304.png)

**Comment by dobrochtaKCI** [comment]
Survey 123 does not allow me to control the message provided when the trashcan is selected to delete a record. We will need to address this during the documentation and training portion of the project.
